# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gophersay < Formula
  desc ""
  homepage "https://github.com/arjundandagi/homebrew-brew"
  version "2.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ArjunDandagi/adcli/releases/download/v2.0.0/adcli_Darwin_arm64.tar.gz"
      sha256 "4d9faa61b53a8edc4cd692f5b4c6ab8d68199d0bc670db311dc26d2d885181cf"

      def install
        bin.install "adcli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ArjunDandagi/adcli/releases/download/v2.0.0/adcli_Darwin_x86_64.tar.gz"
      sha256 "452b571870fe6fdd8c17e60684185f16ace1dbd787c2246537b792b9c5f1c261"

      def install
        bin.install "adcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ArjunDandagi/adcli/releases/download/v2.0.0/adcli_Linux_arm64.tar.gz"
      sha256 "90776b59315b18aa264ce79c0a21f80e5bd6e02e4f0c69b11409b8c955c0a6a0"

      def install
        bin.install "adcli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ArjunDandagi/adcli/releases/download/v2.0.0/adcli_Linux_x86_64.tar.gz"
      sha256 "7c676fecd6efdc2fe94a5d209b2841f4275ac63db08b033316b116abdd04d2fa"

      def install
        bin.install "adcli"
      end
    end
  end
end
