# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cncfctl < Formula
  desc ""
  homepage "https://github.com/arjundandagi/cncfctl"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ArjunDandagi/cncfctl/releases/download/v0.0.1/cncfctl_Darwin_arm64.tar.gz"
      sha256 "afbb6689f3d1a2922322ccfc212770a020ef9bb5b67b790c0aa1a6b463355c00"

      def install
        bin.install "cncfctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ArjunDandagi/cncfctl/releases/download/v0.0.1/cncfctl_Darwin_x86_64.tar.gz"
      sha256 "98278d502aa1e91bfe0b306f3b9e86f804594258a4f42ce532c1be3825cc9f07"

      def install
        bin.install "cncfctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ArjunDandagi/cncfctl/releases/download/v0.0.1/cncfctl_Linux_arm64.tar.gz"
      sha256 "6b541ab0bbf8d03c765bb773d9184ff7f987b4331b5f6912fbf284a23e1d537b"

      def install
        bin.install "cncfctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ArjunDandagi/cncfctl/releases/download/v0.0.1/cncfctl_Linux_x86_64.tar.gz"
      sha256 "25cfdf85a9c272e5bb710606c7c60b6b92731bee7bf9bfbc316a5f34971b31a6"

      def install
        bin.install "cncfctl"
      end
    end
  end
end
